import { Subject } from './types';

export const SUBJECTS: Subject[] = [
  {
    id: 'matematika',
    name: 'Matematika',
    icon: 'Calculator',
    color: '#1d4ed8',
    bgColor: '#dbeafe',
    shadowColor: '#1e3a8a',
    description: 'Angka, rumus, dan logika',
  },
  {
    id: 'bahasa-indonesia',
    name: 'Bahasa Indonesia',
    icon: 'BookOpen',
    color: '#dc2626',
    bgColor: '#fee2e2',
    shadowColor: '#991b1b',
    description: 'Membaca, menulis, tata bahasa',
  },
  {
    id: 'ipa',
    name: 'IPA',
    icon: 'Microscope',
    color: '#16a34a',
    bgColor: '#dcfce7',
    shadowColor: '#15803d',
    description: 'Sains dan alam sekitar',
  },
  {
    id: 'ips',
    name: 'IPS',
    icon: 'Globe',
    color: '#d97706',
    bgColor: '#fef3c7',
    shadowColor: '#b45309',
    description: 'Sejarah, geografi, ekonomi',
  },
  {
    id: 'pkn',
    name: 'PKN',
    icon: 'Flag',
    color: '#dc2626',
    bgColor: '#fee2e2',
    shadowColor: '#991b1b',
    description: 'Pancasila dan kewarganegaraan',
  },
  {
    id: 'bahasa-inggris',
    name: 'Bahasa Inggris',
    icon: 'Languages',
    color: '#7c3aed',
    bgColor: '#ede9fe',
    shadowColor: '#6d28d9',
    description: 'English learning',
  },
  {
    id: 'seni',
    name: 'Seni & Budaya',
    icon: 'Palette',
    color: '#db2777',
    bgColor: '#fce7f3',
    shadowColor: '#be185d',
    description: 'Kreativitas dan budaya',
  },
  {
    id: 'umum',
    name: 'Tanya Bebas',
    icon: 'Sparkles',
    color: '#f97316',
    bgColor: '#ffedd5',
    shadowColor: '#c2410c',
    description: 'Tanya apa saja!',
  },
];
